### ISSUE TITLE
Homebrew release of mapboxcli is broken due to uritemplate.py

### ISSUE THREAD

**Issue by perrygeo** [mapbox/homebrew-cli#1]
```
$ brew install mapbox/cli/mapbox
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (mapbox/cli).
No changes to formulae.

==> Installing mapbox from mapbox/cli
==> Downloading https://files.pythonhosted.org/packages/19/2c/a56df881dbb825465df3a0bb039cb050ccd3de5cf8b604cc7d6b2f71fdcb/mapboxcli-0.5.0.tar.gz
Already downloaded: /Users/mperry/Library/Caches/Homebrew/mapbox-0.5.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/5c/79/5dae7494b9f5ed061cff9a8ab8d6e1f02db352f3facf907d9eb614fb80e9/virtualenv-15.0.2.tar.gz
Already downloaded: /Users/mperry/Library/Caches/Homebrew/mapbox--homebrew-virtualenv-15.0.2.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/mapbox--homebrew-virtualenv-20161122-42835-14qx2bb/target --single-version-externally-
==> python -s /tmp/mapbox--homebrew-virtualenv-20161122-42835-14qx2bb/target/bin/virtualenv -p python /usr/local/Cellar/mapbox/0.5.0/libexec
==> Downloading https://files.pythonhosted.org/packages/8c/d8/1a8d499ab1e5dc50115db17ceacb0e33ec6a3a05d84169841a185ffcf906/boto3-1.4.1.tar.gz
Already downloaded: /Users/mperry/Library/Caches/Homebrew/mapbox--boto3-1.4.1.tar.gz
==> /usr/local/Cellar/mapbox/0.5.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/mapbox--boto3-20161122-42835-1s2j8e
==> Downloading https://files.pythonhosted.org/packages/1c/82/97297c1fac3fd33ed490151e955e57b0d5648c1cef287154b8ef81182edc/botocore-1.4.77.tar.gz
Already downloaded: /Users/mperry/Library/Caches/Homebrew/mapbox--botocore-1.4.77.tar.gz
==> /usr/local/Cellar/mapbox/0.5.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/mapbox--botocore-20161122-42835-167
==> Downloading https://files.pythonhosted.org/packages/c5/cb/7a78039c1e0d4e5fd9d8e9edf7ae34df469267e1c58873ca11af16e96bd8/CacheControl-0.11.7.tar.gz
Already downloaded: /Users/mperry/Library/Caches/Homebrew/mapbox--CacheControl-0.11.7.tar.gz
==> /usr/local/Cellar/mapbox/0.5.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/mapbox--CacheControl-20161122-42835
==> Downloading https://files.pythonhosted.org/packages/7a/00/c14926d8232b36b08218067bcd5853caefb4737cda3f0a47437151344792/click-6.6.tar.gz
Already downloaded: /Users/mperry/Library/Caches/Homebrew/mapbox--click-6.6.tar.gz
==> /usr/local/Cellar/mapbox/0.5.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/mapbox--click-20161122-42835-1edrnm
==> Downloading https://files.pythonhosted.org/packages/77/05/da5c9e19457f20cadfe22c397cd3852577066066f63e40f2baa0831b1693/click-plugins-1.0.3.tar.gz
Already downloaded: /Users/mperry/Library/Caches/Homebrew/mapbox--click-plugins-1.0.3.tar.gz
==> /usr/local/Cellar/mapbox/0.5.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/mapbox--click-plugins-20161122-4283
==> Downloading https://files.pythonhosted.org/packages/fc/53/b89c392f33aa48b3063ad49e4dab70e424659d1fc4103b28b183f477f476/cligj-0.4.0.tar.gz
Already downloaded: /Users/mperry/Library/Caches/Homebrew/mapbox--cligj-0.4.0.tar.gz
==> /usr/local/Cellar/mapbox/0.5.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/mapbox--cligj-20161122-42835-wmwnl0
==> Downloading https://files.pythonhosted.org/packages/37/38/ceda70135b9144d84884ae2fc5886c6baac4edea39550f28bcd144c1234d/docutils-0.12.tar.gz
Already downloaded: /Users/mperry/Library/Caches/Homebrew/mapbox--docutils-0.12.tar.gz
==> /usr/local/Cellar/mapbox/0.5.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/mapbox--docutils-20161122-42835-1dh
==> Downloading https://files.pythonhosted.org/packages/55/db/97c1ca37edab586a1ae03d6892b6633d8eaa23b23ac40c7e5bbc55423c78/futures-3.0.5.tar.gz
Already downloaded: /Users/mperry/Library/Caches/Homebrew/mapbox--futures-3.0.5.tar.gz
==> /usr/local/Cellar/mapbox/0.5.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/mapbox--futures-20161122-42835-u1zz
==> Downloading https://files.pythonhosted.org/packages/6f/93/3e2358e76384ef696cbbce42e92f7ebb422355c015061938e9f2aa2448cd/iso3166-0.7.tar.gz
Already downloaded: /Users/mperry/Library/Caches/Homebrew/mapbox--iso3166-0.7.tar.gz
==> /usr/local/Cellar/mapbox/0.5.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/mapbox--iso3166-20161122-42835-1w8v
==> Downloading https://files.pythonhosted.org/packages/8f/d8/6e3e602a3e90c5e3961d3d159540df6b2ff32f5ab2ee8ee1d28235a425c1/jmespath-0.9.0.tar.gz
Already downloaded: /Users/mperry/Library/Caches/Homebrew/mapbox--jmespath-0.9.0.tar.gz
==> /usr/local/Cellar/mapbox/0.5.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/mapbox--jmespath-20161122-42835-ycd
==> Downloading https://files.pythonhosted.org/packages/bd/61/126f71e29d388eddab120a41c6397f85c79875078c7b511e23b127618107/mapbox-0.10.0.tar.gz
Already downloaded: /Users/mperry/Library/Caches/Homebrew/mapbox--mapbox-0.10.0.tar.gz
==> /usr/local/Cellar/mapbox/0.5.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/mapbox--mapbox-20161122-42835-f7pod
==> Downloading https://files.pythonhosted.org/packages/d6/51/18412cd3977e705f35561b4f286a315c6340654e8d6b4dff0b4a6c04af07/polyline-1.3.1.tar.gz
Already downloaded: /Users/mperry/Library/Caches/Homebrew/mapbox--polyline-1.3.1.tar.gz
==> /usr/local/Cellar/mapbox/0.5.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/mapbox--polyline-20161122-42835-2ti
==> Downloading https://files.pythonhosted.org/packages/51/fc/39a3fbde6864942e8bb24c93663734b74e281b984d1b8c4f95d64b0c21f6/python-dateutil-2.6.0.tar.gz
Already downloaded: /Users/mperry/Library/Caches/Homebrew/mapbox--python-dateutil-2.6.0.tar.gz
==> /usr/local/Cellar/mapbox/0.5.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/mapbox--python-dateutil-20161122-42
==> Downloading https://files.pythonhosted.org/packages/6e/40/7434b2d9fe24107ada25ec90a1fc646e97f346130a2c51aa6a2b1aba28de/requests-2.12.1.tar.gz
Already downloaded: /Users/mperry/Library/Caches/Homebrew/mapbox--requests-2.12.1.tar.gz
==> /usr/local/Cellar/mapbox/0.5.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/mapbox--requests-20161122-42835-wnk
==> Downloading https://files.pythonhosted.org/packages/e6/e0/61bf352050b0d687755cd1a41ead378e6b1b48f8754076c413e816fcc1ee/s3transfer-0.1.9.tar.gz
Already downloaded: /Users/mperry/Library/Caches/Homebrew/mapbox--s3transfer-0.1.9.tar.gz
==> /usr/local/Cellar/mapbox/0.5.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/mapbox--s3transfer-20161122-42835-q
==> Downloading https://files.pythonhosted.org/packages/b3/b2/238e2590826bfdd113244a40d9d3eb26918bd798fc187e2360a8367068db/six-1.10.0.tar.gz
Already downloaded: /Users/mperry/Library/Caches/Homebrew/mapbox--six-1.10.0.tar.gz
==> /usr/local/Cellar/mapbox/0.5.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/mapbox--six-20161122-42835-1c80xr9/
==> Downloading https://files.pythonhosted.org/packages/cd/db/f7b98cdc3f81513fb25d3cbe2501d621882ee81150b745cdd1363278c10a/uritemplate-3.0.0.tar.gz
Already downloaded: /Users/mperry/Library/Caches/Homebrew/mapbox--uritemplate-3.0.0.tar.gz
==> /usr/local/Cellar/mapbox/0.5.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/mapbox--uritemplate-20161122-42835-
==> Downloading https://files.pythonhosted.org/packages/12/97/e12695c7d7710143767022ce931061b4a6b5b19982b20ecf5d71cdde3da1/uritemplate.py-3.0.2.tar.gz
Already downloaded: /Users/mperry/Library/Caches/Homebrew/mapbox--uritemplate.py-3.0.2.tar.gz
==> /usr/local/Cellar/mapbox/0.5.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/mapbox--uritemplate.py-20161122-428
==> /usr/local/Cellar/mapbox/0.5.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/mapbox-20161122-42835-lc54cq/mapbox
🍺  /usr/local/Cellar/mapbox/0.5.0: 2,151 files, 37.7M, built in 25 seconds
```

Looks ok but
```
$ mapbox
Traceback (most recent call last):
  File "/usr/local/bin/mapbox", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/Cellar/mapbox/0.5.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3017, in <module>
    @_call_aside
  File "/usr/local/Cellar/mapbox/0.5.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/Cellar/mapbox/0.5.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/Cellar/mapbox/0.5.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 659, in _build_master
    ws.require(__requires__)
  File "/usr/local/Cellar/mapbox/0.5.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/Cellar/mapbox/0.5.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'uritemplate.py' distribution was not found and is required by mapbox
```

We can workaround this by explicitly installing `uritemplate.py` into the brew venv:

```
$ /usr/local/Cellar/mapbox/0.5.0/libexec/bin/pip install uritemplate.py
Collecting uritemplate.py
  Using cached uritemplate.py-3.0.2-py2.py3-none-any.whl
Requirement already satisfied: uritemplate>=2.0 in /usr/local/Cellar/mapbox/0.5.0/libexec/lib/python2.7/site-packages (from uritemplate.py)
Installing collected packages: uritemplate.py
Successfully installed uritemplate.py-3.0.2
```

But why didn't the version in the initial brew install work??

**Comment by perrygeo** [comment]
Huh, it looks like uritemplate.py is just a deprecated pointer to the uritemplate package. The src_dist installed by the brew install command therefore leaves no evidence of a `uritemplate.py` package. The wheel installed by pip does.

[It's a mess](https://github.com/sigmavirus24/uritemplate/issues/27) but luckily the solution seems to be using only `uritemplate>=2.0`  (no `.py`) as a dep in mapbox-sdk-py. Which means another set of minor releases.
