### ISSUE TITLE
mapbox installation

### ISSUE THREAD

**Issue by tarunluthra** [mapbox/homebrew-cli#5]
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/tmp/mapbox--homebrew-virtualenv-20170914-21178-1tgdzjx/target/bin/virtualenv", line 11, in <module>
    load_entry_point('virtualenv==15.1.0', 'console_scripts', 'virtualenv')()
  File "/tmp/mapbox--homebrew-virtualenv-20170914-21178-1tgdzjx/target/lib/python2.7/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/tmp/mapbox--homebrew-virtualenv-20170914-21178-1tgdzjx/target/lib/python2.7/site-packages/virtualenv.py", line 945, in create_environment
    download=download,
  File "/tmp/mapbox--homebrew-virtualenv-20170914-21178-1tgdzjx/target/lib/python2.7/site-packages/virtualenv.py", line 901, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/tmp/mapbox--homebrew-virtualenv-20170914-21178-1tgdzjx/target/lib/python2.7/site-packages/virtualenv.py", line 797, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /usr/local/Cellar/ma...0/libexec/bin/python - setuptools pip wheel failed with error code 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/mapbox/homebrew-cli/issues

**Comment by perrygeo** [comment]
@tarunluthra we just released a new version, can you try again and let me know if you hit the same error?

**Comment by jparish3** [comment]
Attempt to install on Mojave v10.14.2 with Xcode updated


import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/private/tmp/mapbox--homebrew-virtualenv-20181213-11328-1rewx3r/target
--install-scripts=/private/tmp/mapbox--homebrew-virtualenv-20181213-11328-1rewx3r/target/bin
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/mapbox/homebrew-cli/issues

These open issues may also help:
mapbox installation https://github.com/mapbox/homebrew-cli/issues/5
OS X: mapbox 0.7.1 installation fails (python3) https://github.com/mapbox/homebrew-cli/issues/8

**Comment by sgillies** [comment]
If you have no setuptools module, there's nothing this project can do. Your python needs to be updated. The solution is in here: https://github.com/Homebrew/homebrew-python/issues/216.
