### ISSUE TITLE
Release process broken [SSL: CERTIFICATE_VERIFY_FAILED] 

### ISSUE THREAD

**Issue by perrygeo** [mapbox/homebrew-cli#7]
The final command of the release process outlined [here](https://github.com/mapbox/homebrew-cli/blob/master/release_docs.md) is failing with the following error:

```
⭆ poet -f mapboxcli > ~/work/homebrew-cli/Formula/mapbox.rb
Traceback (most recent call last):
  File "/Users/mperry/env/brewit/bin/poet", line 11, in <module>
    sys.exit(main())
  File "/Users/mperry/env/brewit/lib/python2.7/site-packages/poet/poet.py", line 243, in main
    print(formula_for(args.formula, args.also))
  File "/Users/mperry/env/brewit/lib/python2.7/site-packages/poet/poet.py", line 161, in formula_for
    nodes = merge_graphs(make_graph(p) for p in [package] + also)
  File "/Users/mperry/env/brewit/lib/python2.7/site-packages/poet/poet.py", line 187, in merge_graphs
    for g in graphs:
  File "/Users/mperry/env/brewit/lib/python2.7/site-packages/poet/poet.py", line 161, in <genexpr>
    nodes = merge_graphs(make_graph(p) for p in [package] + also)
  File "/Users/mperry/env/brewit/lib/python2.7/site-packages/poet/poet.py", line 147, in make_graph
    package_data = research_package(package, dependencies[package]['version'])
  File "/Users/mperry/env/brewit/lib/python2.7/site-packages/poet/poet.py", line 80, in research_package
    with closing(urlopen("https://pypi.io/pypi/{}/json".format(name))) as f:
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)>
```

I've upgraded to the latest Python.org version 2.7.15, same result.

@sgillies any thoughts on how to fix this?

**Comment by sgillies** [comment]
@perrygeo Fastly, python.org's CDN, dropped support for old TLS and so this requires an update of OpenSSL and certs in your Python 2.7. It's an extra install step for the Python 2.7.15 binary installer. Look for `Install Certificates.command` in your new installation.

**Comment by perrygeo** [comment]
Thanks @sgillies - this is the command that worked for reference

```
PIP_REQUIRE_VIRTUALENV=false && /Applications/Python\ 2.7/Install\ Certificates.command
```
