### ISSUE TITLE
OS X: mapbox 0.7.1 installation fails (python3)

### ISSUE THREAD

**Issue by JayBrown** [mapbox/homebrew-cli#8]
Error output:

```
Last 15 lines from ~/Library/Logs/Homebrew/mapbox/12.pip:
  Removing source in /private/tmp/pip-req-build-q91pzv91
futures requires Python '>=2.6, <3' but the running Python is 3.6.5
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/mapbox/0.7.1/libexec/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/mapbox/0.7.1/libexec/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 291, in run
    resolver.resolve(requirement_set)
  File "/usr/local/Cellar/mapbox/0.7.1/libexec/lib/python3.6/site-packages/pip/_internal/resolve.py", line 103, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/local/Cellar/mapbox/0.7.1/libexec/lib/python3.6/site-packages/pip/_internal/resolve.py", line 262, in _resolve_one
    check_dist_requires_python(dist)
  File "/usr/local/Cellar/mapbox/0.7.1/libexec/lib/python3.6/site-packages/pip/_internal/utils/packaging.py", line 55, in check_dist_requires_python
    '.'.join(map(str, sys.version_info[:3])),)
pip._internal.exceptions.UnsupportedPythonVersion: futures requires Python '>=2.6, <3' but the running Python is 3.6.5
```

OS X 10.11.6

**Comment by mpatin** [comment]
Running OS X 10.12.6 and having the same issue - I'm running Python 2.7.15 on my machine, but it's being overridden to Python 3 when I run `brew install mapbox/cli/mapbox`

**Comment by JayBrown** [comment]
To clarify: 

```
❯ which -a python python3 | while read -r pythonpath ; do ; echo "$pythonpath" ; $pythonpath --version ; done
/usr/bin/python
Python 2.7.10
/usr/local/bin/python
Python 2.7.15
/usr/local/bin/python3
Python 3.6.5
```

I have Apple's default python installed, which is at v2.7.10 and first in my $PATH, and the other two a secondary installations using Homebrew in /usr/local/bin. So there's a primary macOS default python that's >=2.6, as requested by the mapbox installer, so the error must be in the mapbox CLI installer, not in my (our) system setup(s).

**Comment by JayBrown** [comment]
After upgrading from El Capitan to macOS High Sierra, and also installing the latest Xcode (9.4.1), the mapbox CLI installed fine.

Maybe you should add a system version check in the next mapbox update.

**Comment by sgillies** [comment]
The error is coming from pip, not this project's formula. I suspect updating your Python with homebrew and reinstalling is the solution.
